version: '2'
services:
  web:
    image: custom-odoo:10.0
    command: --update "donation_de,l10n_de_skr49" --database example --addons-path="/mnt/extra-addons,/mnt/donation,/mnt/addons"
    # -u tells Odoo to update a certain addon (e.g. myconferences), you can also put "all"
    # -d specifies the name of the database, here "example"
    # https://stackoverflow.com/questions/44263764/update-all-odoo-modules-in-a-docker-container
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - /Users/franz/git/github/humanilog/donation:/mnt/donation
      - /Users/franz/git/github/humanilog/l10n_de_skr49:/mnt/addons/l10n_de_skr49
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
