version: '3.3'
services:
    postgres:
      image: postgres:9.3 
      volumes:
        - /var/lib/postgresql/data
      environment:
        - POSTGRES_USER=odoo
    odoo:
      build:
        context: ./custom-odoo
        dockerfile: Dockerfile
      image: custom-odoo:9.0
      ports:
        - 8071:8069
      volumes:
        - ./wait-for-it/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
        - ./addons:/mnt/extra-addons
        - ./volumes/odoo/filestore:/opt/odoo/data/filestore
        - ./volumes/odoo/sessions:/opt/odoo/data/sessions
      links:
        - postgres:db
      environment:
        - ODOO_DB_USER=odoo
