version: '3.3'
services:
    postgres:
      image: postgres:9.5 
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=odoo
    odoo:
      image: custom-odoo:11.0
      command: --update all --database dev-setup_postgres_1 
      ports:
        - 127.0.0.1:8069:8069
      volumes:
        - ./addons:/mnt/extra-addons
        - ./volumes/odoo/filestore:/opt/odoo/data/filestore
        - ./volumes/odoo/sessions:/opt/odoo/data/sessions
      links:
        - postgres:db
      environment:
        - ODOO_DB_USER=odoo
